# Generated by Django 5.1.1 on 2024-10-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category_post_description_post_text_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
