# Generated by Django 5.1.1 on 2024-10-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_category_slug_post_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
