# Generated by Django 5.1.1 on 2024-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_path',
            new_name='img_article',
        ),
        migrations.AddField(
            model_name='post',
            name='img_preview',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
