services:
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "80:80"

  django:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile_django
    container_name: django
    restart: always
    volumes:
      - .:/app
    # ports:
    #   - "8000:8000"
    # networks:
    #   inner:
    #     ipv4_address: "172.20.128.2"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:${POSTGRES_DATA}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    # networks:
    #   inner:
    #     ipv4_address: "172.20.128.2"

volumes:
    postgres_data:

# networks:
#   inner:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: "172.20.0.0/16"
#           ip_range: "172.20.0.0/16"