FROM python:3.10

LABEL maintainer="Vladyslav Mishchenko <vmdevspace@gmail.com>"

WORKDIR /app
COPY . .

ARG USERNAME=django
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# RUN apt-get install -y mc 
# RUN apt-get install -y vim

RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["./entrypoint.sh" ]

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

USER $USERNAME

CMD [ "python3" ]