# Generated by Django 5.1.1 on 2024-11-21 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('docs_slug', models.SlugField(max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocsArticle',
            fields=[
                ('title', models.CharField(max_length=256, null=True)),
                ('text', models.TextField(null=True)),
                ('docs_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='docs.docscategory')),
            ],
        ),
    ]
