# Generated by Django 5.1.1 on 2024-11-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocsCategory',
            new_name='DocsLink',
        ),
    ]
